version: "3.9"
services:
  api:
    build: .
    command: ["npm", "run", "start:dev"]
    container_name: card-api
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - mongo
      - redis
    environment:
      - MongoDbUri=mongodb+srv://eren28:28eren57@cluster0.n2gcnhz.mongodb.net/CardSystemDb?retryWrites=true&w=majority&appName=Cluster0
      - RedisUri=redis://redis:6379
      - RMQUri=amqp://guest:guest@rabbitmq:5672
      - EMAIL_USER=m.erenyilmaz2828@gmail.com
      - EMAIL_PASS=oypf iyuf czqg ogwp
      - PRIVATE_KEY=0cRhnlsBY8ghtt?_aJ5q26cMamQY&&

  mongo:
    image: mongo
    container_name: card-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: card-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: card-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-data: